export const levels = [
    {
        level: 1,
        cometCount: 3,
        hasTimer: false,
        cometSpeed: 0,
    },
    {
        level: 2,
        cometCount: 4,
        hasTimer: true,
        timerDuration: 30,
        cometSpeed: 0,
    },
    {
        level: 3,
        cometCount: 4,
        hasTimer: true,
        timerDuration: 15,
        extraTime: 2,
        cometSpeed: 0,
    },
    {
        level: 4,
        cometCount: 5,
        hasTimer: true,
        timerDuration: 15,
        extraTimeI: true,
        extraTimeC:2,
        extraTime: 3,
        gravity: 0.03,
        cometSpeed: 1,
        cometSize: 60,
    },
    {
        level: 5,
        cometCount: 8,
        hasTimer: true,
        timerDuration: 10,
        extraTimeI: true,
        extraTimeC:2,
        extraTime: 2,
        gravity: 0.05,
        cometSize: 70,
        cometSpeed: 2,
    },
];