export const levels = [
    {
        level: 1,
        cometCount: 3,
        hasTimer: false,
        cometSpeed: 0,
        instructions: "Level 1: Get ready to start your journey!",
    },
    {
        level: 2,
        cometCount: 4,
        hasTimer: true,
        timerDuration: 30,
        cometSpeed: 0,
        instructions: "Level 2: Things are getting harder!",
    },
    {
        level: 3,
        cometCount: 4,
        hasTimer: true,
        timerDuration: 15,
        extraTime: 2,
        cometSpeed: 0,
        instructions: "Level 3: Stay focused!",
    },
    {
        level: 4,
        cometCount: 5,
        hasTimer: true,
        timerDuration: 15,
        extraTimeI: true,
        extraTimeC: 2,
        extraTime: 3,
        gravity: 0.03,
        cometSpeed: 1,
        cometSize: 60,
        instructions: "Level 4: It's getting intense!",
    },
    {
        level: 5,
        cometCount: 8,
        hasTimer: true,
        timerDuration: 10,
        extraTimeI: true,
        extraTimeC: 2,
        extraTime: 2,
        gravity: 0.05,
        cometSize: 70,
        cometSpeed: 2,
        instructions: "Level 5: Final challenge. Good luck!",
    },
];
